version: "3.9"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
    networks:
      - cashflow-net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./Rabbitmq/Certs:/certs:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  mongodbStandalone:
    image: mongo:6.0
    container_name: mongodbStandalone
    ports:
      - "27018:27017"
    networks:
      - cashflow-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
  
  eventstore:
    image: eventstore/eventstore:latest
    container_name: eventstore
    environment:
      - EVENTSTORE_DB=eventstore
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=false
      - EVENTSTORE_LOG_LEVEL=Information
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - cashflow-net
    restart: unless-stopped

  transactionservice:
    build:
      context: ./TransactionService
      dockerfile: Dockerfile
    container_name: transactionservice
    ports:
      - "5106:80"
    networks:
      - cashflow-net
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      MongoDb__ConnectionString: mongodb://root:1234@mongodbStandalone:27017
      MongoDb__DatabaseName: CashFlowDb
      MongoDb__CollectionName: transaction
      EventStoreDb__ConnectionString: esdb://eventstore:2113?tls=false
      RabbitMq__Host: rabbitmq
    depends_on:
      - rabbitmq
      - mongodbStandalone
      - eventstore

  consolidationservice:
    build:
      context: ./ConsolidationService
      dockerfile: Dockerfile
    container_name: consolidationservice
    ports:
      - "5010:80"
    networks:
      - cashflow-net
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      MongoDb__ConnectionString: mongodb://root:1234@mongodbStandalone:27017
      MongoDb__DatabaseName: CashFlowDb
      MongoDb__CollectionName: consolidation
      EventStoreDb__ConnectionString: esdb://eventstore:2113?tls=false
      RabbitMq__Host: rabbitmq
    depends_on:
      - rabbitmq
      - mongodbStandalone
      - eventstore

  balanceservice:
    build:
      context: ./BalanceService
      dockerfile: Dockerfile
    container_name: balanceservice
    ports:
      - "5070:80"
    networks:
      - cashflow-net
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      MongoDb__ConnectionString: mongodb://root:1234@mongodbStandalone:27017
      MongoDb__DatabaseName: CashFlowDb
      MongoDb__CollectionName: balance
      EventStoreDb__ConnectionString: esdb://eventstore:2113?tls=false
      RabbitMq__Host: rabbitmq
    depends_on:
      - rabbitmq
      - mongodbStandalone
      - eventstore

  accountservice:
    build:
      context: ./AccountService
      dockerfile: Dockerfile
    container_name: accountservice
    ports:
      - "5020:80"
    networks:
      - cashflow-net
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      MongoDb__ConnectionString: mongodb://root:1234@mongodbStandalone:27017
    depends_on:
      - mongodbStandalone

volumes:
  db_data:

networks:
  cashflow-net:
    external: true
